apiVersion: v2
name: healthcare-platform
description: HIPAA-compliant Healthcare Analytics Platform
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - healthcare
  - analytics
  - hipaa
  - azure
  - data-lake

maintainers:
  - name: Healthcare Analytics Team
    email: admin@healthcareanalytics.com

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
  
  - name: cert-manager
    version: "v1.13.3"
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled
  
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
